# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Willson' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SwiftLint'
  pod 'Alamofire', '~> 4.8.0'
  pod 'AlamofireObjectMapper', '~> 5.2.0'
  pod 'Kingfisher', '~> 4.10.1'
  pod 'ObjectMapper', '~> 3.4.2'
  pod 'DLRadioButton', '~> 1.4'
  pod 'FBSDKLoginKit'
  pod 'KakaoOpenSDK'
  # Pods for Willson

end
